server:
  port: 8770
  
spring:  config:    activate:      on-profile:      - peer1

eureka:
  instance:    appname: eureka-server-clustered
    hostname: eureka-peer1  client:    fetch-registry: true 
    register-with-eureka: true 
    service-url:      defaultZone: http://eureka-peer2:8780/eureka
      

      
---
server:
  port: 8780
  
spring:
  config:
    activate:
      on-profile:
      - peer2
      
eureka:
  instance:
    appname: eureka-server-clustered
    hostname: eureka-peer2
    
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-peer1:8770/eureka
      
