server:
  port: 5050
  
      
spring:  application:    name: customer-service
                
                
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
                