spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: srivatsan
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:    show-sql: true
    hibernate:      ddl-auto: update  
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 
            client-secret: 
            scope:
            - "['read','write']"
            
            