server:
  port: 4080

security:
  oauth2:
    resource:
      token-info-uri: http://localhost:4040/oauth/check_token
    client:
      client-id: myclient
      client-secret: pass123
spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: srivatsan
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update  

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
