server:
  port: 6060

spring:  application:    name: menu-service  
  config:    import: configserver:http://localhost:8888        
    
      boot:    admin:      client:        url:        - http://localhost:9494
        