server:
  port: 6060

spring:  application:    name: menu-service  
    
info:
  build: 
    artifactId: '@project.artifact@'
    groupId: '@project.groupId@'
  java:
    version: '@java.version@'
  author:
    name: srivatsan      
    
    
management:  endpoints:    web:      exposure:        include:        - "*"  
  endpoint:    health:      show-details: always    
    shutdown:      enabled: true  
      
      