resilience4j:
  circuitbreaker:
    instances:
      clientservice:
        registerHealthIndicator: true
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 5
        minimumNumberOfCalls: 3
        permittedNumberOfCallsInHalfOpenState: 2
        slidingWindowSize: 10
        waitDurationInOpenState: 5s
        slidingWindowType: COUNT_BASED

management:
  endpoints:
    web:
      exposure:
        include:
        - "*"        
  endpoint:
    health:
      show-details: always
    circuitbreakers:
      enabled: true
      
  health:
    circuitbreakers:
      enabled: true
